In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv('melb_data.csv')

In [3]:
dataset.head(10)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
5,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.8041,144.9953,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.8060,144.9954,Northern Metropolitan,4019.0
8,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.8008,144.9973,Northern Metropolitan,4019.0
9,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,2.0,220.0,75.0,1900.0,Yarra,-37.8010,144.9989,Northern Metropolitan,4019.0

In [4]:
dataset.shape

(13580, 21)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [6]:
cols = ['Suburb','Address','Rooms','Type','Price','Method','SellerG','Distance','Postcode','Bedroom2','Bathroom','Car','YearBuilt',
        'BuildingArea','Propertycount']

dataset = dataset[cols]

In [7]:
dataset.head(5)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Distance,Postcode,Bedroom2,Bathroom,Car,YearBuilt,BuildingArea,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2.5,3067.0,2.0,1.0,1.0,NaN,NaN,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2.5,3067.0,2.0,1.0,0.0,1900.0,79.0,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2.5,3067.0,3.0,2.0,0.0,1900.0,150.0,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,2.5,3067.0,3.0,2.0,1.0,NaN,NaN,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,2.5,3067.0,3.0,1.0,2.0,2014.0,142.0,4019.0

In [8]:
dataset.shape

(13580, 15)

In [9]:
dataset.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
YearBuilt        5375
BuildingArea     6450
Propertycount       0
dtype: int64

In [10]:
cols_zero = ['Car','YearBuilt']

dataset[cols_zero] = dataset[cols_zero].fillna(0)

In [11]:
dataset.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                 0
YearBuilt           0
BuildingArea     6450
Propertycount       0
dtype: int64

In [12]:
dataset['BuildingArea'] = dataset['BuildingArea'].fillna(dataset.BuildingArea.mean())

In [13]:
dataset.isna().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
YearBuilt        0
BuildingArea     0
Propertycount    0
dtype: int64

In [14]:
dataset = pd.get_dummies(dataset, drop_first=True)
dataset.head(10)

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,YearBuilt,BuildingArea,Propertycount,...,SellerG_Zahn,SellerG_buyMyplace,SellerG_hockingstuart,SellerG_hockingstuart/Advantage,SellerG_hockingstuart/Barry,SellerG_hockingstuart/Village,SellerG_iOne,SellerG_iProperty,SellerG_iSell,SellerG_iTRAK
0,2,1480000.0,2.5,3067.0,2.0,1.0,1.0,0.0,151.96765,4019.0,...,False,False,False,False,False,False,False,False,False,False
1,2,1035000.0,2.5,3067.0,2.0,1.0,0.0,1900.0,79.00000,4019.0,...,False,False,False,False,False,False,False,False,False,False
2,3,1465000.0,2.5,3067.0,3.0,2.0,0.0,1900.0,150.00000,4019.0,...,False,False,False,False,False,False,False,False,False,False
3,3,850000.0,2.5,3067.0,3.0,2.0,1.0,0.0,151.96765,4019.0,...,False,False,False,False,False,False,False,False,False,False
4,4,1600000.0,2.5,3067.0,3.0,1.0,2.0,2014.0,142.00000,4019.0,...,False,False,False,False,False,False,False,False,False,False
5,2,941000.0,2.5,3067.0,2.0,1.0,0.0,0.0,151.96765,4019.0,...,False,False,False,False,False,False,False,False,False,False
6,3,1876000.0,2.5,3067.0,4.0,2.0,0.0,1910.0,210.00000,4019.0,...,False,False,False,False,False,False,False,False,False,False
7,2,1636000.0,2.5,3067.0,2.0,1.0,2.0,1890.0,107.00000,4019.0,...,False,False,False,False,False,False,False,False,False,False
8,1,300000.0,2.5,3067.0,1.0,1.0,1.0,0.0,151.96765,4019.0,...,False,False,False,False,False,False,False,False,False,False
9,2,1097000.0,2.5,3067.0,3.0,1.0,2.0,1900.0,75.00000,4019.0,...,False,False,False,False,False,False,False,False,False,False

In [24]:
dataset.shape

(13580, 13973)

In [16]:
X = dataset.drop('Price', axis = 1)
y = dataset['Price']

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [21]:
train_X,test_X, train_y,test_y = train_test_split(X,y,test_size=0.3,random_state = 42)

In [23]:
reg = LinearRegression().fit(train_X,train_y)

In [26]:
reg.score(train_X,train_y)

0.9999802217245586

In [27]:
reg.score(test_X,test_y)

-9195.105136995126

In [29]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50,max_iter=100,tol=0.1)
lasso_reg.fit(train_X,train_y)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [30]:
lasso_reg.score(train_X,train_y)

0.8646143720854249

In [31]:
lasso_reg.score(test_X,test_y)

0.6624351694941204

In [32]:
from sklearn.linear_model import Ridge

In [33]:
rig = Ridge(alpha=50,max_iter =100, tol=0.1)
rig.fit(train_X,train_y)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [34]:
rig.score(train_X,train_y)

0.663497668661392

In [36]:
rig.score(test_X,test_y)

0.6394609484935525